# Generated by Django 4.1.1 on 2022-10-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.BinaryField()),
            ],
        ),
    ]
